version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto1
    container_name: mosquitto1
    volumes:
      - ./:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001